# Generated by Django 4.2 on 2023-06-05 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Compte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('achat_carte_credit', models.BooleanField(default=False)),
                ('montant', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('heure_envoi', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
